---
logging:
  level:
    org:
      springframework:
        web: INFO

services:
  submission:
    # The initial value of the moving average for fake request delays.
    initial-fake-delay-milliseconds: 10
    # The number of samples for the calculation of the moving average for fake request delays.
    fake-delay-moving-average-samples: 10
    retention-days: 14
    # The number of keys to save to the DB for every real submitted key.
    # Example: If the 'random-key-padding-multiplier' is set to 10, and 5 keys are being submitted,
    # then the 5 real submitted keys will be saved to the DB, plus an additional 45 keys with
    # random 'key_data'. All properties, besides the 'key_data', of the additional keys will be
    # identical to the real key.
    random-key-padding-multiplier: ${RANDOM_KEY_PADDING_MULTIPLIER:1}
    connection-pool-size: 200
    payload:
      max-number-of-keys: 14
    verification:
      base-url: ${VERIFICATION_BASE_URL:http://localhost:8004}
      path: /version/v1/tan/verify
    monitoring:
      batch-size: 5

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration, classpath:/db/specific/{vendor}
    password: ${POSTGRESQL_PASSWORD_FLYWAY:local_setup_flyway}
    user: ${POSTGRESQL_USER_FLYWAY:local_setup_flyway}
# Postgres configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST:localhost}:${POSTGRESQL_SERVICE_PORT:5432}/${POSTGRESQL_DATABASE:cwa}
    username: ${POSTGRESQL_USER_SUBMISSION:local_setup_submission}
    password: ${POSTGRESQL_PASSWORD_SUBMISSION:local_setup_submission}

management:
  server:
    port: 8081
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      group:
        readiness:
          include: db, verificationService
          show-details: always
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    probes:
      enabled: true